### Register Patient
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "full_name": "Cyrus Kimutai",
  "email": "kimtaicyrus@gmail.com",
  "contact_phone": "0722227154",
  "address": "90 Kenya",
  "role": "patient",
  "password": "cyrus1234"
}

### Register Therapist
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "full_name": "Jane Smith",
  "email": "jane.smith@therapy.com",
  "contact_phone": "0789654321",
  "address": "1950 Main St",
  "role": "therapist",
  "specialization": "Cognitive Behavioral Therapy",
  "experience_years": 5,
  "password": "TherapyPro2023!"
}

### Register Admin
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "full_name": "System Administrator",
  "email": "admin@example.com",
  "contact_phone": "0788995544",
  "address": "Admin Headquarters",
  "role": "admin",
  "password": "AdminAccess2023!"
}

### Login User
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "kimtaicyrus@gmail.com",
  "password": "cyrus1234"
}