### Initiate STK Push Payment locally
POST http://localhost:8000/api/mpesa/initiate
Content-Type: application/json

{
  "phoneNumber": "254722227154",
  "amount": 1,
  "referenceCode": "TEST123",
  "description": "Test Payment"
}


### Check Transaction Status (replace with actual checkoutRequestId) locally 
GET http://localhost:8000/api/mpesa/transaction/ws_CO_DMZ_123456789_123456789

### Check Transaction Status (replace with actual checkoutRequestId) on Render
GET https://mpesa-api-billing-system.onrender.com/ws_CO_DMZ_123456789_123456789

### Get All Transactions
GET http://localhost:8000/api/mpesa/transactions

#### Get All Transactions on Render
GET https://mpesa-api-billing-system.onrender.com/api/mpesa/transactions

### M-Pesa Callback Simulation (for testing locally)
# POST http://localhost:8000/api/mpesa/callback
POST https://mpesa-api-billing-system.onrender.com/api/mpesa/callback
Content-Type: application/json

{
  "Body": {
    "stkCallback": {
      "MerchantRequestID": "b54f-471d-93d9-f7f3bf3f7c0e3044622",
      "CheckoutRequestID": "ws_CO_02032025121645976722227154",
      "ResultCode": 0,
      "ResultDesc": "The service request is processed successfully.",
      "CallbackMetadata": {
        "Item": [
          {
            "Name": "Amount",
            "Value": 1
          },
          {
            "Name": "MpesaReceiptNumber",
            "Value": "RAL123456"
          },
          {
            "Name": "TransactionDate",
            "Value": 20220101123456
          },
          {
            "Name": "PhoneNumber",
            "Value": 254712345678
          }
        ]
      }
    }
  }
}